In [1]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
!curl -O https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1089k  100 1089k    0     0  2269k      0 --:--:-- --:--:-- --:--:-- 2283k


In [2]:
# read it in to inspect it
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [4]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
fruits = ["apple", "banana", "mango"]

for i in range(len(fruits)):
    print(i, fruits[i])

 
for i, fruit in enumerate(fruits):
    print(i, fruit)

cars = ['bmv','ferrari', 'porsche']

for j, car in enumerate(cars):
    print(i,car)

students = ["Raj", "Kumar", "Arun"]

for position, student in enumerate(students):
    print(position, student)

stoit = {car: i for i,car in enumerate(cars)}
print(stoit)

0 apple
1 banana
2 mango
0 apple
1 banana
2 mango
2 bmv
2 ferrari
2 porsche
0 Raj
1 Kumar
2 Arun
{'bmv': 0, 'ferrari': 1, 'porsche': 2}


In [6]:
#list 
fruits = ["apple", "banana", "orange", "apple"]

print(fruits[0])


#set
fruits = {"apple", "banana", "orange", "apple"}

print(fruits)

#sorted
numbers = [5, 2, 8, 1, 3]

result = sorted(numbers)

print(result)
# here are all the unique characters that occur in this text
print(set(text))
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

apple
{'apple', 'orange', 'banana'}
[1, 2, 3, 5, 8]
{'L', 'x', 'q', 'Z', 'I', 'N', 'p', ' ', 'c', '!', 'y', 'g', '3', ',', 'P', 'Q', 'j', 'U', 'm', '?', 'H', 'b', 'z', 'o', 'G', 't', 's', 'w', 'S', 'F', 'v', 'J', '&', 'n', 'k', 'a', 'O', 'h', 'A', 'M', ';', 'K', 'R', 'B', "'", 'u', 'r', 'l', 'E', 'C', 'V', 'D', 'X', '$', '\n', 'd', 'f', '.', 'i', ':', '-', 'Y', 'e', 'W', 'T'}

 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [7]:
# import sys
# print(sys.executable)


In [8]:
# %pip install torch torchvision torchaudio

In [9]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

2.13.0+cpu
False


In [10]:
#learn lambda
#lambda arguments: expression
add = lambda x,y:x+y

square = lambda x:x*x
print(add(2, 3))
print(square(2))


5
4


In [11]:
#string to integer and viceverse
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
print(stoi)
print(itos)
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# for c in 'hii there':
#     print(c)
#     print(stoi[c])
print(encode("hii there"))
print(chars[46],chars[46],chars[47])

#decode
print(decode([46,47,47]))
print(decode(encode("hii there")))

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i',

In [12]:
import torch

x = torch.tensor([1, 2, 3])

print(x)

tensor([1, 2, 3])


In [13]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [14]:
# Learning Tensor
import torch

x = torch.tensor([1,2,3])

x = torch.tensor([
    [1,2],
    [3,4]
])


# print(x)


a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

# print(a + b)
# print(a * 2)


import torch

import torch
import torch.nn as nn

# Features
X = torch.tensor([
    [0.5, 0.90],
    [0.2, 0.60],
    [0.8, 0.95],
    [0.1, 0.40],
    [0.7, 0.85]
])

# Labels
y = torch.tensor([
    [1.0],
    [0.0],
    [1.0],
    [0.0],
    [1.0]
])

# Model
model = nn.Linear(2, 1)

# Loss
loss_fn = nn.MSELoss()

# Optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Training
for epoch in range(1000):
    prediction = model(X)

    loss = loss_fn(prediction, y)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

# Test
new_student = torch.tensor([[0.2, 0.40]])

answer = model(new_student)

print(answer)

tensor([[0.1041]], grad_fn=<AddmmBackward0>)


In [15]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
print(n)
train_data = data[:n]
val_data = data[n:]

1003854


In [16]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [17]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [18]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y
